security:
    encoders:
        Acme\UserBundle\Entity\User:
            algorithm: sha1

   
    providers:
        administrators:
            entity: { class: AcmeUserBundle:User, property: username }

    firewalls:
        secured_area:
            pattern:   ^/
            anonymous: ~
            form_login: 
                login_path: acme_home
                check_path: login_check
            logout: 
                path: logout
                target: /

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }